[WIP/RFC] Added a first draft of the sdTestEnvironmentShopware
solutionDrive/sdTestEnvironmentShopware pull request #1
Opened 2018-08-07 21:07 UTC by sd-lueckel

2018-08-08 06:16 UTC, michz requested changes

2018-08-08 06:16 UTC, michz commented on bin/runInSdTest.sh
> +    echo "You must give a version to execute command on, for example 7.1 for PHP 7.1 container."
That not correct.

`echo "You must give a version to execute command on, for example 71 for PHP 7.1 container."`

(Notice the missing dot in version.)

2018-08-08 06:16 UTC, michz commented on etc/scripts/checkSdTestEnvironment.sh
> +    echo "Perhaps forget to run 'vendor/bin/sdTest.sh init'?"
forgot

2018-08-08 06:16 UTC, michz commented on README.md
> +    vendor/bin/runInSdTest.sh 7.1 ./app/install.sh
I think that won't work; See file `bin/runInSdTest.sh`

2018-08-08 06:16 UTC, michz commented on README.md
> +    vendor/bin/runInSdTest.sh 7.1 /bin/bash
I think that won't work; See file `bin/runInSdTest.sh`

2018-08-08 06:17 UTC, michz commented
Generally: I think choosing nginx is a good idea as it is more lightweight than apache, but for real tests depending on shopware's frontend this will bring us trouble as no url rewriting is done up to now, or am I missing something?

2018-08-08 08:06 UTC, sd-lueckel commented
nginx should be ok, we can add some configuration to ensure redirects etc. are working. I will look into it!

2018-08-09 15:30 UTC, sd-lueckel commented
For a fully functional system this pull request (https://github.com/solutionDrive/docker-shopware-container/pull/4) is needed

2018-08-10 14:27 UTC, michz approved these changes

2018-08-10 14:28 UTC, michz commented
solutionDrive/docker-shopware-container#4 is merged.

2018-08-15 11:24 UTC, merged