[RFC|WIP]Add support for different shopware versions
solutionDrive/sdTestEnvironmentShopware pull request #18
Opened 2018-12-13 14:59 UTC by solutionDrive-Alt

This PR should result in scripts that can handle multiple `shopware`-versions and fixes #17 . At the moment the scripts are tied to `shopware 5.4`.

At the moment, the current solution in this PR results in rather ugly calls to the scripts like:
```bash
$  vendor/bin/sdPlugin.sh 70 52 add
```
where the parts are:
``` bash
$  vendor/bin/sdPlugin.sh 70                      52                          add
    ____________|__________  __|__                  __|__                         __|__
                   script              php-version   Shopware-Version  subcommand
```

What do you think would be a nice way to get rid of this amount of parameters, which are not very self-explanatory.

One possibility could be to run the scripts for all versions and give the user the abiltiy to exclude php-/shopware-versions.

2018-12-19 08:24 UTC, sd-lueckel requested changes
I think it is ok for now but for the future we should think about a more flexible way

2018-12-19 08:24 UTC, sd-lueckel commented on README.md
> +
I think this newline is not necessary

2019-01-28 15:31 UTC, sd-lueckel submitted a review, later dismissed

2019-02-04 09:43 UTC, michz submitted a review, later dismissed

2019-02-04 09:48 UTC, Jnoack331 submitted a review, later dismissed

2019-02-06 09:09 UTC, sd-lueckel approved these changes

2019-02-06 13:14 UTC, michz approved these changes

2019-02-06 13:14 UTC, merged