Bug/issue 2 run in sd test not working
solutionDrive/sdTestEnvironmentShopware pull request #3
Opened 2018-08-15 14:32 UTC by twojtylak

fixes #2

2018-08-15 14:44 UTC, sd-lueckel submitted a review, later dismissed

2018-08-15 15:22 UTC, michz requested changes

2018-08-15 15:22 UTC, michz commented on bin/runInSdTest.sh
> +WORK_DIR="/var/www/shopware54_php${VERSION}"
I'm not happy that you removed the ability to change the workdir from outside bash script.
_(EDIT: I mean from "outside the bash script", not "outside the container")_

What do you think about following?

```
WORK_DIR=${WORK_DIR:-"/var/www/shopware54_php${VERSION}"}
```

2018-08-16 07:21 UTC, twojtylak commented on bin/runInSdTest.sh
> +WORK_DIR="/var/www/shopware54_php${VERSION}"
Ah okay. I never got the idea to change the workdir by argument.
You want to be able to call e.g.
```
vendor/bin/runInSdTest.sh 72 WORK_DIR="var/www" bin/console sw:cache:clear
```
right?

Unfortunately we need to exclude this argument in the docker exec because all parameters except the first one are passed to docker exec.

Also it would break, at the moment, if workdir is passed as first argument.

2018-08-16 07:24 UTC, michz commented on bin/runInSdTest.sh
> +WORK_DIR="/var/www/shopware54_php${VERSION}"
No, I want to be able to do this:

```
WORK_DIR="/somewhere/else" vendor/bin/runInSdTest.sh 72 bin/console sw:cache:clear
```

This passes WORK_DIR as environment variable to the called script, without adding it to the global environment of the current shell.

See also for an explanation (with definition) :
https://unix.stackexchange.com/a/126942

2018-08-16 07:26 UTC, twojtylak commented on bin/runInSdTest.sh
> +WORK_DIR="/var/www/shopware54_php${VERSION}"
👍 ah okay thats fine (and working). I will change it.

2018-08-16 07:33 UTC, michz approved these changes

2018-08-16 07:54 UTC, sd-lueckel approved these changes

2018-08-16 07:54 UTC, merged